version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: bwapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bWAPP
    networks:
      - bwapp_net

  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    ports:
      - "9090:80"
    depends_on:
      - mysql
    networks:
      - bwapp_net

networks:
  bwapp_net:
    driver: bridge
